#################################
#######################################
######## Author: PhoenixRa ##########
############### 2022 ##################
#################################
######## Links ##########
# Spigot: https://www.spigotmc.org/members/phoenixra.969595/
# YouTube: https://www.youtube.com/channel/UCPlvJUaG6ZfdYasCjSFHoqw
# GitHub: https://github.com/Phoenix-Ra
######## Contact Info ##########
# Discord: https://discord.gg/R2Wk5ZRXxp
#################################

metrics: true
CheckIPOnJoin: true
KickUnauthorizedOp: true
TabBlocker: true
CommandBlocker: true
UUIDSpoofFix: true
DiscordBot:
  active: false
  guildID: your_guild_id
  bot_token: your_bot_token
  admin_ds-role: id_of_the_role_which_is_allowed_to_use_commands
  cmds-on-login:
    - deop {player}
  cmds-on-verify:
    - op {player}
PermsChecker:
  active: true
  permissions:
  - '*'
  - server_defence.admin
FixSyntax:
  active: true
  whitelist-cmds:
  - /serverdefence

modsBlocker:
  fabric:
    enabled: true
    punishment:
    - kick {player} &cFabric usage detected
  forge:
    enabled: true
    punishment:
    - kick {player} &cForge usage detected
  liteLoader:
    enabled: true
    punishment:
    - kick {player} &cLiteLoader usage detected
  rift:
    enabled: true
    punishment:
    - kick {player} &cRift usage detected
  winterWare:
    enabled: true
    punishment:
    - kick {player} &cWinterWare usage detected
  vape:
    enabled: true
    punishment:
    - kick {player} &cVape usage detected
  hyperium:
    enabled: true
    punishment:
    - kick {player} &cHyperium usage detected
  pixelClient:
    enabled: true
    punishment:
    - kick {player} &cPixelClient usage detected
  lunarClient:
    enabled: true
    punishment:
    - kick {player} &cLunarClient usage detected
  emc:
    enabled: true
    punishment:
    - kick {player} &cEmc usage detected
  schematica:
    enabled: true
  5zig:
    enabled: true
  betterSprinting:
    enabled: true
  worldDownloader:
    enabled: true
