name: ServerDefence
main: FenixRa.ServerDefence.Main
version: 3.0.2
website: https://www.spigotmc.org/resources/100438/
description: Server Defence system
commands:
  serverdefence:
    description: main command
    usage: /sd help
    aliases: [sd]

  permissions:
    serverDef.admin:
      description: Allows the usage of all commands
      default: op