name: ServerDefence
main: me.phoenixra.serverdefence.Main
version: ${projectVersion}
website: https://www.spigotmc.org/resources/100438/
description: Server Defence system
author: PhoenixRa
commands:
  serverdefence:
    description: main command
    usage: /sd help
    aliases: [sd]

  permissions:
    serverDef.admin:
      description: Allows the usage of all commands
      default: op