forceCheckOnJoin: true
server-name: name
ops:
  - Be
ips:
  - /127.0.0.0
opsOnlyPerms:
  - '*'
FixSyntax:
  active: true
  whitelist-plugins:
    - PrimeSpace_BanSystem
donationProtect:
  enabled: true
  donaters:
    - Fenixx
    - Dangerous
  passwords:
    Fenixx: DJhf9wj332
    Dangerous: Hrty2398dja