name: PrimeSpace_Protection
main: ru.PrimeSpace.FenixRa.Protection.Protection
version: 0.1
depend: [ProtocolLib]
description: >
  Server Protection
commands:
  protection:
    description: Settings for admins
    usage: /protection [arg]
  code:
    description: Top donaters
    usage: /code [arg]